---
- hosts: all
  become: true

  tasks:
    - name: Remove Docker Engine packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-ce-rootless-extras
        state: absent
        purge: true
        autoremove: true
        update_cache: true

    - name: Remove Docker configuration files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/docker
        - /etc/default/docker
        - /var/lib/docker
        - /var/lib/containerd

